sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
   - line=$(cat CMakeLists.txt | grep "project(.*)" -o); tmp=${line:8}; proj_name=${tmp:0:${#tmp}-1}; # parse the project name
  - source /opt/ros/melodic/setup.bash
  - rosdoc_lite . # generate the documentation
  - grep -rl "mrs_msgs/html" doc | xargs sed -i 's+../../../mrs_msgs/html/+../+g' # remove the html part of paths in the generated files
  - grep -rl "std_msgs/html" doc | xargs sed -i 's+../../../std_msgs/html/+http://docs.ros.org/melodic/api/std_msgs/html/+g' # remove the html part of paths in the generated files
  - grep -rl "geometry_msgs/html" doc | xargs sed -i 's+../../../geometry_msgs/html/+http://docs.ros.org/melodic/api/geometry_msgs/html/+g' # remove the html part of paths in the generated files
  - cd doc/html; ln -s index-msg.html index.html # link index.html to index-msg.html so that a browser opens that by default

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master