language: generic

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      env: BADGE=bionic
    - os: linux
      dist: focal
      env: BADGE=focal
    - stage: documentation
      os: linux
      dist: bionic
      before_install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        - sudo apt -y update
        - sudo apt -y install ros-melodic-rosdoc-lite
      script:
        - line=$(cat CMakeLists.txt | grep "project(.*)" -o); tmp=${line:8}; proj_name=${tmp:0:${#tmp}-1}; # parse the project name
        - source /opt/ros/melodic/setup.bash
        - rosdoc_lite . # generate the documentation
        - grep -rl "mrs_msgs/html" doc | xargs sed -i 's+../../../mrs_msgs/html/+../+g' # remove the html part of paths in the generated files
        - grep -rl "std_msgs/html" doc | xargs sed -i 's+../../../std_msgs/html/+http://docs.ros.org/melodic/api/std_msgs/html/+g' # remove the html part of paths in the generated files
        - grep -rl "geometry_msgs/html" doc | xargs sed -i 's+../../../geometry_msgs/html/+http://docs.ros.org/melodic/api/geometry_msgs/html/+g' # remove the html part of paths in the generated files
        - cd doc/html; ln -s index-msg.html index.html # link index.html to index-msg.html so that a browser opens that by default
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: doc/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
  allow_failures:
    - env: BADGE=focal

branches:
  only:
    - master

compiler:
- gcc

before_install:
- ./.ci/ci_before_install.sh

before_script: 

script:
- ./.ci/ci_test_build.sh
